python harmonic.py --tau 0.1
python harmonic.py --tau 0.15
python harmonic.py --tau 0.2
python harmonic.py --tau 0.25
python harmonic.py --tau 0.3
python harmonic.py --tau 0.35
python harmonic.py --tau 0.4
python harmonic.py --tau 0.5
python harmonic.py --tau 1.0
python harmonic.py --tau 2.0
python harmonic.py --tau 5.0
python harmonic.py --tau 10.0
python harmonic.py --tau 25.0
python harmonic.py --tau 50.0