python harmonic_optimal.py --tau 0.1
python harmonic_optimal.py --tau 0.15
python harmonic_optimal.py --tau 0.2
python harmonic_optimal.py --tau 0.25
python harmonic_optimal.py --tau 0.3
python harmonic_optimal.py --tau 0.35
python harmonic_optimal.py --tau 0.4
python harmonic_optimal.py --tau 0.5
python harmonic_optimal.py --tau 1.0
python harmonic_optimal.py --tau 2.0
python harmonic_optimal.py --tau 5.0
python harmonic_optimal.py --tau 10.0
python harmonic_optimal.py --tau 25.0
python harmonic_optimal.py --tau 50.0