python linear.py --tau 0.1
python linear.py --tau 0.15
python linear.py --tau 0.2
python linear.py --tau 0.25
python linear.py --tau 0.3
python linear.py --tau 0.35
python linear.py --tau 0.4
python linear.py --tau 0.5
python linear.py --tau 1.0
python linear.py --tau 2.0
python linear.py --tau 5.0
python linear.py --tau 10.0
python linear.py --tau 25.0
python linear.py --tau 50.0